# version format
version: 2.7.2.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

# Test against this version of Node.js
#environment:
#  ruby_version: 22-x64
#  nodejs_version: "4"
#
#cache:
#- C:\Ruby%ruby_version%\lib\ruby\gems -> appveyor.yml
#- C:\projects\merchello\src\Merchello.Web.UI.Client\node_modules -> appveyor.yml
#- C:\projects\merchello\src\packages -> appveyor.yml
# Another
#
## Install scripts. (runs after repo cloning)
#install:
#  #- git clone https://github.com/sass/sassc.git
#  #- git clone https://github.com/sass/sass-spec.git
#  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
#  - gem install sass
#  # Get the latest stable version of Node.js or io.js
#  - ps: Install-Product node $env:nodejs_version
#  # install modules
#  - cmd: ECHO Changing directory to Merchello.Web.UI.Client
#  - ps: cd  src\Merchello.Web.UI.Client
#  - npm install
#  - npm install -g grunt-cli
#  - ps: grunt build
#  - cmd: ECHO Changing directory back to Merchello
#  - ps: cd  ..\..
#  - cmd: ECHO Changing directory to Merchello.Providers.UI.Client
#  - ps: cd src\Merchello.Providers.UI.Client
#  - npm install
#  - ps: grunt build
#  - cmd: ECHO Changing directory back to Merchello
#  - ps: cd  ..\..
#  - cmd: ECHO Changing directory to Merchello.Mui.Client
#  - ps: cd src\Merchello.Mui.Client
#  - npm install
#  - ps: grunt build
#  - cmd: ECHO Changing directory back to Merchello
#  - ps: cd  ..\..

build_script:
- build-appveyor.cmd

test: off

image: Visual Studio 2017

#test:
#   assemblies:
#      - '..\test\Merchello.Tests.IntegrationTests\bin\Release\Merchello.Tests.IntegrationTests.dll'

# run custom scripts before tests
before_test:

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
  # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/merchello-dev/api/v2
    symbol_server: https://www.myget.org/F/merchello-dev/api/v2/package
    api_key: 5d653b55-54d4-44ab-94d6-b6997af31bf6
    artifact: /.*\.nupkg/
    on:
      branch: merchello-dev

  # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: X9DSeYEmUc7IQBYgj1SuiDhpb/FpPBWrE2LeRBA6mayUstv4bRcpNucipYcqsQcI
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

  # NuGet Deployment for releases
  - provider: NuGet
    server: 
    api_key:
      secure: hbZFYwZU83KRyLOFBL2FDoc0BI6A6Z1dOZCXMqeOVZTA6UHD0+hGxX3e0lWMs4Up
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true

# scripts to run after deployment
after_deploy:
   # run tests
   #- nunit-console test\Merchello.Tests.IntegrationTests\bin\Release\Merchello.Tests.IntegrationTests.dll /exclude:LongRunning /xml .\nunit-results.xml
   # upload results to AppVeyor
   #- $wc = New-Object 'System.Net.WebClient'
   #- $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nunit-results.xml))
